# The URL the site will be built for
base_url = "https://USERNAME.github.io/sha-zola-vonge"  # <-- replace with your site URL
theme = "vonge"

title = "Vonge"
author = "Vanessa Marley"
description = "Vonge is a portfolio site template for Zola"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_feeds = true
feed_filenames = [ "atom.xml",]
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    { name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
logo_image = "images/logo.svg"
social_media_share_image = "/images/01.jpg"
disqus_identifier = ""
google_analytics = ""
twitter_handle = ""

author_image = '/images/avatar.jpg'

navigation = [
    { url = "$BASE_URL", title = "Home" },
    { url = "$BASE_URL/projects", title = "Projects" },
    { url = "$BASE_URL/posts", title = "Blog" },
    { url = "$BASE_URL/tags", title = "Tags" },
    { url = "", title = "Pages", submenu = [
        { url = "$BASE_URL/about", title = "About" },
        { url = "$BASE_URL/elements", title = "Elements" }
    ] }
]
social_icons = [
    { url = "https://github.com/cydave", icon = "GitHub" },
    { url = "https://twitter.com/_cydave", icon = "Twitter" },
    { url = "$BASE_URL/atom.xml", icon = "RSS" },
    { url = "https://pinterest.com", icon = "Pinterest"},
]
date_format = "%d %b %Y"
language_direction = "auto"
keywords = ["keyword1", "keyword2", "keyword3"]

[extra.newsletter]
newsletter_title = "Join my mailing list"
newsletter_identifier = ""
newsletter_button = "Subscribe"
newsletter_description = "Get inspiration, updates and, cool stuff!"

[extra.footer]
menu = [
    { url = "$BASE_URL", title = "Home" },
    { url = "$BASE_URL/projects/", title = "Projects" },
    { url = "$BASE_URL/elements/", title = "Elements" },
    { url = "$BASE_URL/about/", title = "About" },
    { url = "$BASE_URL/posts/", title = "Blog" },
]
#copyright = ""


[[extra.content_blocks]]
block = "hero"
title = "Hi there, I am Vanessa Marley"
description_html = "<strong>Photographer</strong> and Visual Content Strategist from Albany. I work as a lifestyle, product, and landscape photographer, creating images for a diverse range of requests, from online media to printed artwork."
image = "/images/01.jpg"
image_alt = "Vanessa Marley's picture"
cta_button_link = "#contact"
cta_button = "Get in touch"
works_button_link = "#projects"
works_button = "See my works"
[[extra.content_blocks]]
block = "projects-section"
title = "Latest Works"
description_html = """
    <p>I show only my best works built completely with passion, simplicity,
    and creativity!</p>"""
link_url = "/projects"
show_projects = true
[[extra.content_blocks]]
block = "testimonials-section"
title = "Happy Clients"
description_html = ""
show_testimonials = true
[[extra.content_blocks]]
block = "blog-section"
title = "Recent Posts"
description_html = """
    <p>Vonge blog features productivity, tips, inspiration and strategies for
    massive profits. Find out how to set up a successful blog or how to make
    yours even better!</p>"""
link_url = "/posts"
show_posts = true
[[extra.content_blocks]]
block = "newsletter"
newsletter_title = "Join my mailing list"
newsletter_description = "Get inspiration, updates and, cool stuff!"
newsletter_identifier = ""
newsletter_button = "Subscribe"
[[extra.content_blocks]]
block = "contact-form"
form_title = "Get in touch"
form_description = "Vonge comes with a built-in contact form."
form_success_page = ''
form_submission_email = "site@example.com"
form_button_text = "Send now"
